---
- name: Add apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_url: "{{ nginx_key_url }}"
    aptkey_name: "{{ nginx_key_name }}"
    aptkey_path: "{{ nginx_key_path }}"

- name: Ensure that repositories are installed
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ nginx_repositories }}"

- name: Ensure that packages are installed
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ nginx_packages }}"
