---
- name: Add repositories for nginx and install it
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories: "{{ nginx_repositories }}"
    installer_packages: "{{ nginx_packages }}"

- name: Copy nginx snippets files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nginx_snippets_path }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
    mode: "{{ nginx_file_mode }}"
    force: true
  with_fileglob:
    - "{{ nginx_local_snippets_path }}/*"

- name: Copy nginx config file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nginx_path }}/{{ item | basename }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
    mode: "{{ nginx_file_mode }}"
    force: true
  with_first_found:
    - files:
        - "{{ nginx_local_config_file }}"
      skip: true
  notify:
    - test configuration
    - restart nginx

- name: Disable default site
  become: true
  ansible.builtin.file:
    path: "{{ nginx_sites_enabled_path }}/default"
    state: absent
  notify:
    - test configuration
    - restart nginx

- name: Copy nginx sites configuration files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nginx_sites_available_path }}"
    owner: "{{ nginx_sites_available_owner }}"
    group: "{{ nginx_sites_available_group }}"
    mode: "{{ nginx_sites_available_mode }}"
    force: true
  with_fileglob:
    - "{{ nginx_local_sites_available_path }}/*"

- name: Enable sites
  become: true
  ansible.builtin.file:
    path: "{{ nginx_sites_enabled_path }}/{{ item | basename }}"
    src: "{{ nginx_sites_available_path }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ nginx_local_path }}/*"
  notify:
    - test configuration
    - restart nginx
