---
- name: Install nginx
  when: nginx_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Uninstall nginx
  when: nginx_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml

    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
