---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ nginx_autoremove }}"
    purge: "{{ nginx_purge }}"
    state: absent
  loop: "{{ nginx_packages }}"

- name: Ensure that repositories are uninstalled
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: absent
  loop: "{{ nginx_repositories }}"

- name: Remove apt key
  ansible.builtin.import_role:
    name: ansible-role-aptkey
  vars:
    aptkey_name: "{{ nginx_key_name }}"
    aptkey_path: "{{ nginx_key_path }}"
    aptkey_uninstall: true
